USE AdventureWorks2019
GO

--DATETIME FUNCTIONS

--GETDATE() --> WILL RETURN THE CURRENT DATE ALONG WITH TIME
SELECT GETDATE()

--ISDATE() --> CHECKS AN EXPRESSION AND RETURNS 1 IF IT IS A VALID DATE
SELECT ISDATE(GETDATE())
SELECT ISDATE('1999-04-28') 

--DAY() --> RETURNS THE DAY OF THE MONTH FOR A SPECIFIED DATE(1-31)
SELECT DAY(GETDATE())
SELECT DAY('1999-04-28') 

--MONTH() --> RETURNS THE MONTH PART FOR A SPECIFIED DATE(1-12)
SELECT MONTH(GETDATE())
SELECT MONTH('1999-04-28')

--YEAR() --> RETURNS THE YEAR PART FOR A SPECIFIED DATE
SELECT YEAR(GETDATE())
SELECT YEAR('1999-04-28')

--DATEPART() --> WILL RETURN THE PART OF DATE OR TIME -- RETURNS INTEGER
SELECT DATEPART(YEAR,'1999-04-28 04:55:20')

--DATENAME() --> WILL RETURN THE PART OF DATE OR TIME - RETURNS A STRING(Nvarchar)
SELECT DATENAME(MONTH,'1999-04-28 04:55:20')

--DATEADD() --> ADDS A TIME/DATE INTERVAL TO A DATE AND THEN RETURNS THE DATE
SELECT DATEADD(DAY,6,'1999-04-28')

--DATEDIFF() --> WILL DISPLAY THE DATE AND TIME BETWEEN TWO DATES
SELECT DATEDIFF(DAY,'1999-04-28',GETDATE())

