USE AdventureWorks2019
GO

--STRING FUNCTIONS

--LEN() --> RETURNS THE LENGHT OF A STRING
SELECT LEN('ADVENTURE WORKS')

--LEFT() --> EXTRACTS A NUMBER OF CHARACTERS FROM A STRING (STARTING FROM THE LEFT)
SELECT LEFT('ADVENTURE WORKS',4)

--TRIM() --> REMOVES LEADING AND TRAILING SPACES FROM A STRING
-- LTRIM() REMOVES LEFT SPACES --- RTRIM() REMOVES RIGHT SPACES
SELECT TRIM('ADVENTURE   WORKS   2019      ')

--LOWER() --> CONVERTS A STRING TO LOWER-CASE
SELECT LOWER('ADVENTURE WORKS 2019')

--UPPER() --> CONVERTS A STRING TO UPPER-CASE
SELECT UPPER('adventure works 2019')

SELECT UPPER(FirstName), UPPER(LastName)
FROM Person.Person

--REVERSE() --> REVERSES A STRING AND RETURNS THE RESULT
SELECT REVERSE('Federico')

--REPLACE() --> REPLACES ALL OCCURRENCES OF A SUBSTRING WITHIN A STRING, WITH A NEW SUBSTRING
SELECT REPLACE('FEDERICO','CO','CK')

--SUBSTRING() --> EXTRACTS SOME CHARACTERS FROM A STRING
SELECT SUBSTRING('ADVENTURE WORKS 2019',4,9)