USE AdventureWorks2019
GO

--MATH FUNCTIONS

--ABS() --> RETURNS THE ABSOLUTE VALUE OF A NUMBER
SELECT ABS(-303)

--AVG() --> AGGREGATE FUNCTION, RETURNS THE AVERAGE VALUE OF AN EXPRESSION
-- WE USE GROUP BY AND HAVING WITH AVG
--What is the average list price of all the products?
SELECT AVG(ListPrice)
FROM Production.Product


--CEILING() --> RETURNS THE SMALLEST INTEGER VALUE THAT IS >= A NUMBER
SELECT CEILING(15.50)

--FLOOR() --> RETURNS THE LARGEST INTEGER VALUE THAT IS <= A NUMBER
SELECT FLOOR(15.75)

--COUNT() --> AGGREGATE FUNCTION, RETURNS THE NUMBER OF RECORDS RETURNED BY A SELECT QUERY
--How many products are in the Product table?
SELECT COUNT(*)
FROM Production.Product


--MAX() --> AGGREGATE FUNCTION, RETURNS THE MAXIMUM VALUE IN A SET OF VALUES
-- Max list price?
SELECT MAX(ListPrice)
FROM Production.Product

--MIN --> AGGREGATE FUNCTION, RETURNS THE MINIMUM VALUE IN A SET OF VALUES
-- MIN list price?
SELECT MIN(ListPrice)
FROM Production.Product

--POWER() --> RETURNS THE VALUE OF A NUMBER RAISED TO THE POWER OF ANOTHER NUMBER
--POWER(BASE,EXPONENT)
SELECT POWER(4,2) 

--RAND() --> RETURNS A RANDOM NUMBER
SELECT RAND() --IF NO SEED IS SPECIFIED, IT WILL RETURN A RANDOM NUMBER BETWEEN 0 AND 1, 0-1 NOT INCLUSIVE
SELECT RAND(5) --RETURNS THE SAME NUMBER
SELECT RAND()*10 --RETURNS A RANDOM NUMBER BETWEEN 0-10, FLOAT
SELECT FLOOR(RAND()*10) --RETURNS AN INTEGER NUMBER

--ROUND() --> ROUNDS A NUMBER TO A SPECIFIED NUMBER OF DECIMAL PLACES
--ROUND(NUMBER,DECIMALS,OPERATIONS)
SELECT ROUND(123.321,1,0)

--SQRT() --> RETURNS THE SQUARE ROOT OF A NUMBER
SELECT SQRT(16)

--SQUARE() --> RETURNS THE SQUARE OF A NUMBER
SELECT SQUARE(16) -- 16*16=256

--SUM() --> AGGREGATE FUNCTION, CALCULATES THE SUM OF A SET OF VALUES
SELECT SUM(ListPrice)
FROM Production.Product
